
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Admin_Signup extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs =null;
    PreparedStatement pst=null;

    /**
     * Creates new form Admin_Signup
     */
    public Admin_Signup() {
        initComponents();
        conn=javaconnect.ConnercrDb();
        
    }
    
    public void close(){
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        admin_mobile = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        admin_gender_male = new javax.swing.JCheckBox();
        admin_first_name = new javax.swing.JTextField();
        admin_last_name = new javax.swing.JTextField();
        signup_icon_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin_username = new javax.swing.JTextField();
        admin_gender_female = new javax.swing.JCheckBox();
        admin_employment_no = new javax.swing.JTextField();
        admin_email_address = new javax.swing.JTextField();
        Admin_Signup_Button = new javax.swing.JButton();
        employmentNo_warning = new javax.swing.JLabel();
        firstName_warning = new javax.swing.JLabel();
        lastName_warning = new javax.swing.JLabel();
        username_warning = new javax.swing.JLabel();
        emailAddress_warning = new javax.swing.JLabel();
        mobile_warning = new javax.swing.JLabel();
        password_warning = new javax.swing.JLabel();
        retypePassword_warning = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        admin_pass = new javax.swing.JPasswordField();
        admin_pass_retype = new javax.swing.JPasswordField();
        confirm_pass_checkbox = new javax.swing.JCheckBox();
        passMatch_warning = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        admin_mobile.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        admin_mobile.setOpaque(false);
        admin_mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_mobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_mobileFocusLost(evt);
            }
        });
        admin_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_mobileActionPerformed(evt);
            }
        });
        admin_mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_mobileKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("University of Eldoret Administrative Sign Up Form");

        buttonGroup1.add(admin_gender_male);
        admin_gender_male.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N
        admin_gender_male.setText("Male");
        admin_gender_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_gender_maleActionPerformed(evt);
            }
        });

        admin_first_name.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        admin_first_name.setOpaque(false);
        admin_first_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_first_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_first_nameFocusLost(evt);
            }
        });
        admin_first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_first_nameActionPerformed(evt);
            }
        });
        admin_first_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_first_nameKeyReleased(evt);
            }
        });

        admin_last_name.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        admin_last_name.setOpaque(false);
        admin_last_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_last_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_last_nameFocusLost(evt);
            }
        });
        admin_last_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_last_nameKeyReleased(evt);
            }
        });

        signup_icon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UoE_Dark.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel4.setText("Gender");

        admin_username.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        admin_username.setOpaque(false);
        admin_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_usernameFocusLost(evt);
            }
        });
        admin_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_usernameActionPerformed(evt);
            }
        });
        admin_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_usernameKeyReleased(evt);
            }
        });

        buttonGroup1.add(admin_gender_female);
        admin_gender_female.setFont(new java.awt.Font("Franklin Gothic Book", 0, 11)); // NOI18N
        admin_gender_female.setText("Female");
        admin_gender_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_gender_femaleActionPerformed(evt);
            }
        });

        admin_employment_no.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        admin_employment_no.setOpaque(false);
        admin_employment_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_employment_noFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_employment_noFocusLost(evt);
            }
        });
        admin_employment_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_employment_noActionPerformed(evt);
            }
        });
        admin_employment_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_employment_noKeyReleased(evt);
            }
        });

        admin_email_address.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        admin_email_address.setOpaque(false);
        admin_email_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_email_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_email_addressFocusLost(evt);
            }
        });
        admin_email_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_email_addressActionPerformed(evt);
            }
        });
        admin_email_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_email_addressKeyReleased(evt);
            }
        });

        Admin_Signup_Button.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        Admin_Signup_Button.setText("Sign Up");
        Admin_Signup_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Signup_ButtonActionPerformed(evt);
            }
        });
        Admin_Signup_Button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Admin_Signup_ButtonKeyPressed(evt);
            }
        });

        employmentNo_warning.setForeground(new java.awt.Color(255, 0, 0));

        firstName_warning.setForeground(new java.awt.Color(255, 0, 0));

        lastName_warning.setForeground(new java.awt.Color(255, 0, 0));

        username_warning.setForeground(new java.awt.Color(255, 0, 0));

        emailAddress_warning.setForeground(new java.awt.Color(255, 0, 0));

        mobile_warning.setForeground(new java.awt.Color(255, 0, 0));

        password_warning.setForeground(new java.awt.Color(255, 0, 0));
        password_warning.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_warningKeyReleased(evt);
            }
        });

        retypePassword_warning.setForeground(new java.awt.Color(255, 0, 0));
        retypePassword_warning.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                retypePassword_warningKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel5.setText("Employment No");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel6.setText("First Name");

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel7.setText("Last Name");

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel8.setText("Email Address");

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel9.setText("Mobile");

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel10.setText("Enter Username");

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel11.setText("Password");

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jLabel12.setText("Confirm Password");

        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Go back to");

        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Login");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addGap(2, 2, 2))
        );

        admin_pass.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        admin_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_passActionPerformed(evt);
            }
        });
        admin_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_passKeyReleased(evt);
            }
        });

        admin_pass_retype.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        admin_pass_retype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_pass_retypeKeyReleased(evt);
            }
        });

        confirm_pass_checkbox.setText("Show Password");
        confirm_pass_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_pass_checkboxActionPerformed(evt);
            }
        });

        passMatch_warning.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        passMatch_warning.setForeground(new java.awt.Color(255, 0, 0));
        passMatch_warning.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(signup_icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(admin_employment_no)
                                    .addComponent(employmentNo_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(admin_mobile)
                                    .addComponent(mobile_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(admin_first_name)
                                    .addComponent(admin_last_name)
                                    .addComponent(admin_email_address)
                                    .addComponent(firstName_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastName_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailAddress_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(admin_pass)
                                            .addComponent(admin_username)
                                            .addComponent(username_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Admin_Signup_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(password_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(retypePassword_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(passMatch_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(confirm_pass_checkbox))
                                            .addComponent(admin_pass_retype)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(admin_gender_female)
                                            .addComponent(admin_gender_male))
                                        .addGap(112, 112, 112)))))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signup_icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(admin_employment_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(employmentNo_warning))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(admin_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(username_warning)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(admin_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_warning)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(firstName_warning)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_pass_retype, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lastName_warning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_email_address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(emailAddress_warning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(mobile_warning)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(retypePassword_warning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passMatch_warning)
                            .addComponent(confirm_pass_checkbox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(admin_gender_male))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_gender_female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Admin_Signup_Button)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(610, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admin_email_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_email_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_email_addressActionPerformed

    private void admin_gender_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_gender_femaleActionPerformed
        // TODO add your handling code here:
        gender="female";
    }//GEN-LAST:event_admin_gender_femaleActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       // UOE Icon resizing call

        BufferedImage originalImage = null;
        int type = 0;
        try{
            originalImage = ImageIO.read(new File("C:\\Users\\pc\\Documents\\NetBeansProjects\\Exam_Authentication_Sys\\src\\images\\UoE_Dark.png"));
            type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
        
            }catch (IOException ex){
                Logger.getLogger(Admin_Login.class.getName()).log(Level.SEVERE, null, ex);
                }
        int h = signup_icon_label.getHeight();
        int w = signup_icon_label.getWidth();
        ImageIcon icon1 = new ImageIcon(FunctionControl.scaleimage(originalImage, w, h, type));
        signup_icon_label.setIcon(icon1);
    }//GEN-LAST:event_formWindowActivated

    private void Admin_Signup_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Signup_ButtonActionPerformed
        // TODO add your handling code here:
        
         
        //Check if fields are empty or not
        if(admin_employment_no.getText().trim().isEmpty() && admin_first_name.getText().trim().isEmpty() && 
           admin_last_name.getText().trim().isEmpty() && admin_username.getText().trim().isEmpty() && 
           admin_email_address.getText().trim().isEmpty() && admin_mobile.getText().trim().isEmpty() && 
           admin_pass.getText().trim().isEmpty() && admin_pass_retype.getText().trim().isEmpty()){
            
            employmentNo_warning.setText("Employment No required");
            firstName_warning.setText("First name is empty");
            lastName_warning.setText("Last name is empty");
            username_warning.setText("Username not set");
            emailAddress_warning.setText("Invalid email");
            mobile_warning.setText("Mobile is empty");
            password_warning.setText("Field is empty");
            retypePassword_warning.setText("Field is empty");
        
        }
        else if(admin_employment_no.getText().trim().isEmpty()){
            employmentNo_warning.setText("Employment No required");
        }
        else if(admin_first_name.getText().trim().isEmpty()){
            firstName_warning.setText("First name is empty");
        }
        else if(admin_last_name.getText().trim().isEmpty()){
            lastName_warning.setText("Last name is empty");
        }
        else if(admin_username.getText().trim().isEmpty()){
            username_warning.setText("Username not set");
        }
        else if(admin_email_address.getText().trim().isEmpty()){
            emailAddress_warning.setText("Invalid email");
        }
        else if(admin_mobile.getText().trim().isEmpty()){
             mobile_warning.setText("Mobile is empty");
        }
        else if(admin_pass.getText().trim().isEmpty()){
            password_warning.setText("Field is empty");
        }
        else if(admin_pass_retype.getText().trim().isEmpty()){
             retypePassword_warning.setText("Field is empty");
        }
        else if(admin_pass.getText().trim() == null ? admin_pass_retype.getText().trim() != null : !admin_pass.getText().trim().equals(admin_pass_retype.getText().trim())){
             //JOptionPane.showMessageDialog(null, "Password Dont Match");
             passMatch_warning.setText("PASSWORD DO NOT MATCH");
        }
        else{
        
        try{
            String sql ="insert into admin_login (employment_no, first_name, last_name, username, email, mobile, password, gender) values (?,?,?,?,?,?,?,?)";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, admin_employment_no.getText());
            pst.setString(2, admin_first_name.getText());
            pst.setString(3, admin_last_name.getText());
            pst.setString(4, admin_username.getText());
            pst.setString(5, admin_email_address.getText());
            pst.setString(6, admin_mobile.getText());
            pst.setString(7, admin_pass.getText());
            pst.setString(8, gender);
            
            pst.execute();
            
//            //Confirmation to save student dialog box
//            
//            String confirm="<html> Student Id = "+studentid.getText()+" <br>"
//                                + "First Name = "+student_firstname.getText()+"<br>"
//                                + "Surname = "+student_surname.getText()+"</html>";
//            JOptionPane optionpane = new JOptionPane();
//            optionpane.setMessage(confirm);
//            optionpane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
//            JDialog dialog = optionpane.createDialog(null, "SAVE NEW STUDENT?");
//            dialog.setVisible(true);
//            //Confirmation to save student dialog box
            
            JOptionPane.showMessageDialog(null, "Sign up Successfull");
        
        
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                }
                try{
                close();
                Admin_Login login = new Admin_Login();
                login.setVisible(true);
                    }catch(Exception e){}
            }
        
    }//GEN-LAST:event_Admin_Signup_ButtonActionPerformed

    private void Admin_Signup_ButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Admin_Signup_ButtonKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
        //Check if fields are empty or not
        if(admin_employment_no.getText().trim().isEmpty() && admin_first_name.getText().trim().isEmpty() && 
           admin_last_name.getText().trim().isEmpty() && admin_username.getText().trim().isEmpty() && 
           admin_email_address.getText().trim().isEmpty() && admin_mobile.getText().trim().isEmpty() && 
           admin_pass.getText().trim().isEmpty() && admin_pass_retype.getText().trim().isEmpty()){
            
            employmentNo_warning.setText("Employment No required");
            firstName_warning.setText("First name is empty");
            lastName_warning.setText("Last name is empty");
            username_warning.setText("Username not set");
            emailAddress_warning.setText("Invalid email");
            mobile_warning.setText("Mobile is empty");
            password_warning.setText("Field is empty");
            retypePassword_warning.setText("Field is empty");
        
        }
        else if(admin_employment_no.getText().trim().isEmpty()){
            employmentNo_warning.setText("Employment No required");
        }
        else if(admin_first_name.getText().trim().isEmpty()){
            firstName_warning.setText("First name is empty");
        }
        else if(admin_last_name.getText().trim().isEmpty()){
            lastName_warning.setText("Last name is empty");
        }
        else if(admin_username.getText().trim().isEmpty()){
            username_warning.setText("Username not set");
        }
        else if(admin_email_address.getText().trim().isEmpty()){
            emailAddress_warning.setText("Invalid email");
        }
        else if(admin_mobile.getText().trim().isEmpty()){
             mobile_warning.setText("Mobile is empty");
        }
        else if(admin_pass.getText().trim().isEmpty()){
            password_warning.setText("Field is empty");
        }
        else if(admin_pass_retype.getText().trim().isEmpty()){
             retypePassword_warning.setText("Field is empty");
        }
        else if(admin_pass.getText().trim() == null ? admin_pass_retype.getText().trim() != null : !admin_pass.getText().trim().equals(admin_pass_retype.getText().trim())){
             
             passMatch_warning.setText("PASSWORD DO NOT MATCH");
        }
        else{
        
        try{
            String sql ="insert into admin_login (employment_no, first_name, last_name, username, email, mobile, password, gender) values (?,?,?,?,?,?,?,?)";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, admin_employment_no.getText());
            pst.setString(2, admin_first_name.getText());
            pst.setString(3, admin_last_name.getText());
            pst.setString(4, admin_username.getText());
            pst.setString(5, admin_email_address.getText());
            pst.setString(6, admin_mobile.getText());
            pst.setString(7, admin_pass.getText());
            pst.setString(8, gender);
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Sign up Successfull");
        
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_Admin_Signup_ButtonKeyPressed

    private void admin_employment_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_employment_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_employment_noActionPerformed

    private void admin_first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_first_nameActionPerformed

    private void admin_employment_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_employment_noFocusGained
       
    }//GEN-LAST:event_admin_employment_noFocusGained

    private void admin_employment_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_employment_noFocusLost

    }//GEN-LAST:event_admin_employment_noFocusLost

    private void admin_first_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_first_nameFocusGained

    }//GEN-LAST:event_admin_first_nameFocusGained

    private void admin_first_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_first_nameFocusLost
        
    }//GEN-LAST:event_admin_first_nameFocusLost

    private void admin_last_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_last_nameFocusGained

    }//GEN-LAST:event_admin_last_nameFocusGained

    private void admin_last_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_last_nameFocusLost

    }//GEN-LAST:event_admin_last_nameFocusLost

    private void admin_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_usernameActionPerformed

    private void admin_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_usernameFocusGained
        
    }//GEN-LAST:event_admin_usernameFocusGained

    private void admin_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_usernameFocusLost

    }//GEN-LAST:event_admin_usernameFocusLost

    private void admin_email_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_email_addressFocusGained

    }//GEN-LAST:event_admin_email_addressFocusGained

    private void admin_email_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_email_addressFocusLost
  
    }//GEN-LAST:event_admin_email_addressFocusLost

    private void admin_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_mobileActionPerformed

    }//GEN-LAST:event_admin_mobileActionPerformed

    private void admin_mobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_mobileFocusGained
  
    }//GEN-LAST:event_admin_mobileFocusGained

    private void admin_mobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_mobileFocusLost
   
    }//GEN-LAST:event_admin_mobileFocusLost

    private void admin_employment_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_employment_noKeyReleased
        // TODO add your handling code here:
        employmentNo_warning.setText("");
    }//GEN-LAST:event_admin_employment_noKeyReleased

    private void admin_first_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_first_nameKeyReleased
        // TODO add your handling code here:
        firstName_warning.setText("");
    }//GEN-LAST:event_admin_first_nameKeyReleased

    private void admin_last_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_last_nameKeyReleased
        // TODO add your handling code here:
        lastName_warning.setText("");
    }//GEN-LAST:event_admin_last_nameKeyReleased

    private void admin_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_usernameKeyReleased
        // TODO add your handling code here:
        username_warning.setText("");
    }//GEN-LAST:event_admin_usernameKeyReleased

    private void admin_email_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_email_addressKeyReleased
        // TODO add your handling code here:
        emailAddress_warning.setText("");
    }//GEN-LAST:event_admin_email_addressKeyReleased

    private void admin_mobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_mobileKeyReleased
        // TODO add your handling code here:
        mobile_warning.setText("");
    }//GEN-LAST:event_admin_mobileKeyReleased

    private void admin_gender_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_gender_maleActionPerformed
        // TODO add your handling code here:
        gender="male";
    }//GEN-LAST:event_admin_gender_maleActionPerformed

    private void password_warningKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_warningKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_password_warningKeyReleased

    private void retypePassword_warningKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_retypePassword_warningKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_retypePassword_warningKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:
        close();
        Admin_Login login = new Admin_Login();
        login.setVisible(true);
    }//GEN-LAST:event_jLabel13MousePressed

    private void admin_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_passActionPerformed

    private void confirm_pass_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_pass_checkboxActionPerformed
        // Password Setting Visible
        if(confirm_pass_checkbox.isSelected()){
            admin_pass_retype.setEchoChar((char)0);
            admin_pass.setEchoChar((char)0);
        }else {
            admin_pass_retype.setEchoChar('*');
            admin_pass.setEchoChar('*');
            }
    }//GEN-LAST:event_confirm_pass_checkboxActionPerformed

    private void admin_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_passKeyReleased
        // TODO add your handling code here:
        password_warning.setText("");
        passMatch_warning.setText("");
    }//GEN-LAST:event_admin_passKeyReleased

    private void admin_pass_retypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_pass_retypeKeyReleased
        // TODO add your handling code here:
        retypePassword_warning.setText("");
        passMatch_warning.setText("");
    }//GEN-LAST:event_admin_pass_retypeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_Signup_Button;
    private javax.swing.JTextField admin_email_address;
    private javax.swing.JTextField admin_employment_no;
    private javax.swing.JTextField admin_first_name;
    private javax.swing.JCheckBox admin_gender_female;
    private javax.swing.JCheckBox admin_gender_male;
    private javax.swing.JTextField admin_last_name;
    private javax.swing.JTextField admin_mobile;
    private javax.swing.JPasswordField admin_pass;
    private javax.swing.JPasswordField admin_pass_retype;
    private javax.swing.JTextField admin_username;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox confirm_pass_checkbox;
    private javax.swing.JLabel emailAddress_warning;
    private javax.swing.JLabel employmentNo_warning;
    private javax.swing.JLabel firstName_warning;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastName_warning;
    private javax.swing.JLabel mobile_warning;
    private javax.swing.JLabel passMatch_warning;
    private javax.swing.JLabel password_warning;
    private javax.swing.JLabel retypePassword_warning;
    private javax.swing.JLabel signup_icon_label;
    private javax.swing.JLabel username_warning;
    // End of variables declaration//GEN-END:variables


    private String gender;
}
